---
- hosts: "all"
  remote_user: "roman"
  become: true
  become_user: "root"
  become_method: "sudo"
  force_handlers: true
  vars_files:
    - "vars.yml"
  handlers:
    - import_tasks: "handlers/main.yml"

  tasks:
    - name: "configure locales"
      include_tasks: "tasks/locale.yml"

    - name: "connect to wifi"
      include_tasks: "tasks/wifi.yml"

    - name: "configure ssh"
      include_tasks: "tasks/ssh.yml"

    - name: "update package manager"
      include_tasks: "tasks/packagemanager.yml"

    - name: "install packages"
      include_tasks: "tasks/packages.yml"

    - name: "configure firewall"
      include_tasks: "tasks/firewall.yml"

    - name: "install python from source"
      vars:
        - py_version: "3.6.4"
      include_tasks: "tasks/python.yml"