---
- hosts: "all"
  vars_files:
    - "vars.yml"
  remote_user: "{{ remote_user }}"
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:
  - name: "add new user"
    include_tasks: "tasks/useradd.yml"

- hosts: "all"
  vars_files:
    - "vars.yml"
  remote_user: "{{ new_username }}"
  become: true
  become_user: "root"
  become_method: "sudo"

  tasks:
    - name: "configure system"
      include_tasks: "tasks/system.yml"

    - name: "configure wifi"
      include_tasks: "tasks/wifi.yml"

    - name: "configure SSH"
      include_tasks: "tasks/ssh.yml"

    - name: "install packages"
      include_tasks: "tasks/packages.yml"

    - name: "configure firewall"
      include_tasks: "tasks/firewall.yml"

    - name: "install git and authorize GitHub"
      include_tasks: "tasks/git.yml"

    - name: "install Python from source"
      vars:
        - py_version: "3.6.4"
      include_tasks: "tasks/python.yml"

    - name: "install Telegram bots"
      include_tasks: "tasks/telegram.yml"

    - name: "install Telegram bots"
      include_tasks: "tasks/telegram.yml"

    - name: "configure AFP"
      vars:
        - netatalk_version: "3.1.11"
      include_tasks: "tasks/afp.yml"

    - name: "install Home Assistant"
      include_tasks: "tasks/hass.yml"

#    - name: "configure webserver"
#      vars:
#        - dhparam_size: 4096
#      include_tasks: "tasks/webserver.yml"

    - name: "remove default user"
      include_tasks: "tasks/userremove.yml"

    - name: "add motd"
      include_tasks: "tasks/motd.yml"

