---
- hosts: "all"
  vars_files:
    - "vars.yml"
  remote_user: "{{ remote_user }}"
  become: true
  become_user: "root"
  become_method: "sudo"
  force_handlers: true
  handlers:
    - import_tasks: "handlers/main.yml"

  vars_prompt:
    - name: system_hostname
      prompt: "Enter a new hostname for the system"
      private: no

    - name: user_password
      prompt: "Enter a password for the user account that will be created"
      private: yes

  tasks:
    - name: "configure system"
      include_tasks: "tasks/system.yml"

    - name: "configure wifi"
      include_tasks: "tasks/wifi.yml"

    - name: "configure SSH"
      include_tasks: "tasks/ssh.yml"

    - name: "install packages"
      include_tasks: "tasks/packages.yml"

    - name: "configure firewall"
      include_tasks: "tasks/firewall.yml"

    - name: "install Python from source"
      vars:
        - py_version: "3.6.4"
      include_tasks: "tasks/python.yml"

    - name: "configure AFP"
      vars:
        - netatalk_version: "3.1.11"
      include_tasks: "tasks/afp.yml"

    - name: "install Home Assistant"
      include_tasks: "tasks/hass.yml"

    - name: "replace default user"
      include_tasks: "tasks/user.yml"

    - name: "add motd"
      include_tasks: "tasks/motd.yml"

