---
# Needed because of Ansible issue #25414
- name: "check if unattended-upgrades is not in progress"
  shell:
    "while fuser /var/lib/dpkg/lock; do sleep 1; done;"
  become: true
  changed_when: false

- name: "upgrade packages"
  apt:
    upgrade: "yes"
    update_cache: true
    cache_valid_time: 100

- name: "install apt packages"
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "tmux"
    - "vim"
