---
- name: "install Python packages and dependencies"
  package:
    name: "{{ item }}"
    state: "latest"
  with_items:
    - "build-essential"
    - "tk-dev"
    - "libncurses5-dev"
    - "libncursesw5-dev"
    - "libreadline6-dev"
    - "libdb5.3-dev"
    - "libgdbm-dev"
    - "libsqlite3-dev"
    - "libssl-dev"
    - "libbz2-dev"
    - "libexpat1-dev"
    - "liblzma-dev"
    - "zlib1g-dev"
    - "python3-pip"
    - "virtualenv"

- set_fact:
    py_version_short: "{{ '.'.join(py_version.split('.', 2)[:2]) }}"

- set_fact:
    py_exec: "python{{ py_version_short }}"

- name: "check if python version installed"
  command: "which {{ py_exec }}"
  register: command_result
  ignore_errors: yes

- name: "download the tar ball"
  get_url:
    url: "https://www.python.org/ftp/python/{{ py_version }}/Python-{{ py_version }}.tgz"
    dest: "/tmp/Python-{{ py_version }}.tgz"
  #when: command_result.rc != 0

- name: "unpack the source package"
  unarchive:
    src: "/tmp/Python-{{ py_version }}.tgz"
    dest: "/tmp/"
    copy: no
  #when: command_result.rc != 0

- name: "run configure"
  command: "./configure"
  args:
    chdir: "/tmp/Python-{{ py_version }}"
  #when: command_result.rc != 0

- name: "run make"
  command: "make"
  args:
    chdir: "/tmp/Python-{{ py_version }}"
  #when: command_result.rc != 0

- name: "run make install"
  command: "make install"
  args:
    chdir: "/tmp/Python-{{ py_version }}"
  #when: command_result.rc != 0

- name: "clean up the source files"
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "/tmp/Python-{{ py_version }}"
    - "/tmp/Python-{{ py_version }}.tgz"
