---
- name: Install Java
  package:
    name: openjdk-8-jre-headless
    state: latest

- name: Download .deb package
  get_url:
    url: https://dl.ui.com/unifi/5.12.66/unifi_sysvinit_all.deb
    dest: /tmp/unifi.deb

- name: Install .deb package
  apt:
    deb: /tmp/unifi.deb
