---
- name: Install setup-tools
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-pip

- pip:
    name: docker-compose~=1.23.0

- name: Create directory
  file:
    path: /var/docker/unms
    state: directory

- name: Copy docker-compose
  copy:
    src: "templates{{ item }}"
    dest: "{{ item }}"
  with_items:
    - /var/docker/unms/docker-compose.yml

# docker-compose up -d
