---
- name: "create user"
  user:
    name: "{{ new_username }}"
    comment: "{{ new_user_full_name }}"
    password: "{{ new_user_password }}"
    generate_ssh_key: yes
    groups: adm, dialout, cdrom, sudo, audio, video, plugdev, games, users, input, netdev, spi, i2c, gpio,
    append: yes


#- name: "remove pi user"
#- user:
#    name: pi
#    state: absent
#    remove: yes